# Generated by Django 3.2.8 on 2022-02-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_image',
            field=models.ImageField(default='https://i.imgur.com/kWiAYZR.jpg', upload_to='banner_pics'),
        ),
    ]
