# Generated by Django 3.2.8 on 2022-02-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bg_image',
            field=models.ImageField(default='programming_bg.jpg', upload_to='banner_pics'),
        ),
    ]
