# Generated by Django 3.2.8 on 2022-02-02 13:59

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
