# Generated by Django 3.2.8 on 2022-03-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
